version: '3.8'

services:
  ml_service:
    build: .
    environment:
      - REDIS_URL=redis://redis_db:6379
    volumes:
      - ./models:/app/models  # Mount models directory
    networks:
      - ml_service_network

volumes:
  redis_data: 

networks:
  ml_service_network:
    external: true
    name: ml_service_network